### ISSUE TITLE
bug bitgesell bridge

### ISSUE THREAD

**Issue by maicontavora** [BitgesellOfficial/wbgl-bridge#1]
Hi I have a problem with the bitgesell bridge   
I made a deposit and it still hasn't crashed. usually takes 3 confirmations
Wrapped BGL (WBGL) on Ethereum blockchain: 
prints https://drive.google.com/drive/folders/1udN5Y4HSTMemAZ51rhPkQye31_9SsIzH
there was no bridge from BG to WBGL. of reimbursement of 1912.54166956 BGL
https://bgl.bitaps.com/e6e7c5a2375faf7fb030ea310b16d465ff725c589805206894d77742a0b03084
https://bscscan.com/token/0x2ba64efb7a4ec8983e22a49c81fa216ac33f383a?a=0x821cd256954554196fd4ad4bc034f53de685ca7a

**Comment by leetdev** [comment]
Your BGL was returned to the originating address due to insufficient WBGL balance. Transaction:

https://bgl.bitaps.com/644c17d26ba7377a0c4fb153dbe19b8c4052524ab6aae03b0a6663bb30c68aee

**Comment by maicontavora** [comment]
this was the first time. there was another shipment. had enough money. the
second time i won'th. the one that was not returned  ttps://
bgl.bitaps.com/e6e7c5a2375faf7fb030ea310b16d465ff725c589805206894d77742a0b03084/bgl1q4w3c28ldytzjn05q6znduscs8y2tpjqtuply3y

https://bgl.bitaps.com/e6e7c5a2375faf7fb030ea310b16d465ff725c589805206894d77742a0b03084/bgl1qu3f0xuxtntsqq0jzcyp0jzj2ffgwng4l3gfqy2
[image: image.png]

Em sáb., 18 de set. de 2021 às 10:25, Rene Aavik ***@***.***>
escreveu:

**Comment by leetdev** [comment]
I see, the exact same amount confused me. I see the transaction marked as pending in the database, perhaps there was a momentary issue with the BSC API at that moment. I will look into it.

**Comment by leetdev** [comment]
I have refreshed the pending transaction. Since there was not enough WBGL balance to complete the conversion, your BGL was automatically returned to you. https://bgl.bitaps.com/faf01fd213d2bff7720fb782ea7b473b182236ae7d917006912477b12ca9f29c

I apologize for the inconvenience. I will look into stabilizing the service to prevent this sort of thing from happening in the future.

**Comment by maicontavora** [comment]
thank you very much .i understand. today I had an answer. I received the
BGL. the first time I refund. still had 7200 available.

Em sáb., 18 de set. de 2021 às 12:02, Rene Aavik ***@***.***>
escreveu:
