### ISSUE TITLE
I used bglswap and I didn't receive bgl in my wallet 

### ISSUE THREAD

**Issue by maicontavora** [BitgesellOfficial/wbgl-bridge#26]
hello, I subscribed to this address bgl1qetdj5z3p8ngv3ea54n4lxepthquqay8zl8fwqs I used bglswap and I didn't receive bgl in my wallet bglswap wallet bgl1qetdj5z3p8ngv3ea54n4lxepthquqay8zl8fwqs nwallet  bscsca you should get 0x525D5cF032223BC6EDE50D6a7Cb2f8220F8b6bc5

Bitgesell transaction https://bgl.bitaps.com/b542c04dd9f66ffc3a31f7eda93ba30ea5ca30f4ac92efa93915b605551b96a1/bgl1q4w3c28ldytzjn05q6znduscs8y2tpjqtuply3y

**Comment by d-lobo** [comment]
Same issue on using the bridge for token swap on BSC chains. For eth-based chains it seems to work.

**Comment by maicontavora** [comment]
for erc20 eth network it works.  only for the bscscan network, which does
not work, I have already made several transfers, even used other wallets
from both networks.  and did not complete or return

Em ter, 11 de abr de 2023 04:07, d-lobo ***@***.***> escreveu:

**Comment by d-lobo** [comment]
just to add: the bridge in opposite direction wbgl -> bgl works also fine, only bgl -> wbgl seems stuck
