### ISSUE TITLE
I used bglswap and I didn't receive bgl in my wallet

### ISSUE THREAD

**Issue by maicontavora** [BitgesellOfficial/wbgl-bridge#27]
hello, I made a transfer to the bridge.today BGL to WBGL bsc did not arrive in metamask and mem was returned wallet  
 bgl1qetdj5z3p8ngv3ea54n4lxepthquqay8zl8fwqs wallet bscscam 0x525D5cF032223BC6EDE50D6a7Cb2f8220F8b6bc5
 https://bgl.bitaps.com/9f7000b76878a8d4ab0dabdce3701f3a662021f5c6291afe4f9864fed2a5da7a/bgl1qetdj5z3p8ngv3ea54n4lxepthquqay8zl8fwqs

**Comment by globalbtc1** [comment]
I'm also having the same issue, and this doesn't seem to be a blockchain issue but the problem is in the keys which they control
